version: "3.7"

x-node: &default-node
  build:
    context: ../src/
  image: cannon

  networks:
    - cannon-demo
  volumes:
    - ./proto:/app/proto/
    - ./configs/:/app/configs/
  command: "./cannon run -c /app/configs/config.yaml"
  restart: on-failure
  depends_on:
    - locust
    - ping_service

services:
  ping_service:
    ports:
      - 9600:9600
    build:
      context: pingService
    image: cannon_ping_service
    container_name: cannon_ping_service
    networks:
      - cannon-demo

  locust:
    ports:
      - 8089:8089
      - 5557:5557
    image: grubykarol/locust
    container_name: locust
    environment:
      - "ATTACKED_HOST=http://locust:8089"
      - "LOCUST_MODE=master"
    networks:
      - cannon-demo
    volumes:
      - ./locust:/locust

  # You need configuration user at dashboard: localhost:9999
  # influxdb:
  #   ports:
  #     - 9999:9999
  #   image: quay.io/influxdb/influxdb:2.0.0-beta
  #   networks:
  #     - cannon-demo

  cannon:
    <<: *default-node
    container_name: cannon

  cannon1:
    <<: *default-node
    container_name: cannon1

networks:
  cannon-demo:
