language: go

go:
  - 1.13.6

branches:
  only:
  - feature/Integrate-TravisCI  

before_script:
  - cd src

jobs:
  include:
    - stage: build
      script: go build ./cmd/cannon
    - stage: test
      script: echo "Test 01"
    -
      script: echo "Test 02"
    - stage: push-docker-registry
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker build -t zpx-cannon .
        - docker tag zpx-cannon $DOCKER_USER/zpx-cannon:latest
        - docker push $DOCKER_USER/zpx-cannon:latest