language: go

go:
  - 1.13.6

branches:
  only:
  - feature/Integrate-TravisCI  

before_script:
  - cd src

jobs:
  include:
    - stage: build
      script: go build ./cmd/cannon
    - stage: test
      script: echo "Test 01"
    -
      script: echo "Test 02"
    - stage: push-docker-registry
      script:
        - docker build -t registry-gitlab.zalopay.vn/ci-cd/cannon .
        - docker push registry-gitlab.zalopay.vn/ci-cd/cannon