language: go

go:
  - 1.13.6

branches:
  only:
  - feature/Integrate-TravisCI  

before_script:
  - cd src

jobs:
  include:
    - stage: build
        script: go build ./cmd/cannon
    - stage: test
        script: echo "Test 01"
        script: echo "Test 02"
