LocustWebTarget: "http://0.0.0.0:8089/"
LocustHost: "127.0.0.1"
LocustPort: 5557

NoWorkers: 800
HatchRate: 10

IsPersistent: "false"
DatabaseAddr: "http://0.0.0.0:9999"
Token: "egc6_K6V0pCmEwIahIzm9i52ommTcsa7TS5XtmcSBnR9VeX31dMsRJ_STN-bUqOwWW77vPiU0aM9RGMQFwxT-A=="
Bucket: "benchmark-results"
Origin: "tranndc"

GRPCPort: 4770
GRPCHost: "localhost"

Method: "zas.protobuf.TransactionService.transRecord"
Proto: "./transaction.proto"
